version: '3'
services:
  epozoriste-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - epozoristenet

  epozoriste-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=epozoriste-sql,1433;Database=160029;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 56404:80
    networks:
      - epozoristenet
    links:
      - epozoriste-sql
    depends_on:
      - epozoriste-sql

networks:
  epozoristenet:
    driver: bridge