//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoriste.Mobile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pozoriste.Mobile.TestResource", typeof(TestResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozorište u Mostaru središnja je i najstarija pozorišna institucija u BiH, u kojoj djeluju tri ansambla: operni, dramski i baletni.
        ///Kao središnja nacionalna kuća pozorište u Mostaru njeguje raznovrstan program uz djela domaćih autora različitih stilova i razdoblja..
        /// </summary>
        public static string About_Text {
            get {
                return ResourceManager.GetString("About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nama.
        /// </summary>
        public static string About_us {
            get {
                return ResourceManager.GetString("About_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glumci.
        /// </summary>
        public static string Actors {
            get {
                return ResourceManager.GetString("Actors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumenti.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galerija.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žanr.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nagradne igre.
        /// </summary>
        public static string Giveaways {
            get {
                return ResourceManager.GetString("Giveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocjenjivanje.
        /// </summary>
        public static string Grading {
            get {
                return ResourceManager.GetString("Grading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historija.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javna ustanova Narodno pozorište u Mostaru osnovana je 28. novembra 1949. godine..
        /// </summary>
        public static string History_Text {
            get {
                return ResourceManager.GetString("History_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjava.
        /// </summary>
        public static string Log_out {
            get {
                return ResourceManager.GetString("Log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnički profil.
        /// </summary>
        public static string My_account {
            get {
                return ResourceManager.GetString("My_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje rezervacije.
        /// </summary>
        public static string My_reservations {
            get {
                return ResourceManager.GetString("My_reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje ulaznice.
        /// </summary>
        public static string My_tickets {
            get {
                return ResourceManager.GetString("My_tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novosti.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifikacije.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kako do nas.
        /// </summary>
        public static string Our_location {
            get {
                return ResourceManager.GetString("Our_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikazivanja.
        /// </summary>
        public static string Performances {
            get {
                return ResourceManager.GetString("Performances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predstave.
        /// </summary>
        public static string Shows {
            get {
                return ResourceManager.GetString("Shows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
